fix: helm unittest install failing
The latest version of helm unittest requires helm v3.18.0 or later
according to https://github.com/helm-unittest/helm-unittest/issues/790

The plugin fails to install in GHA with:

```
// helm plugin install https://github.com/helm-unittest/helm-unittest
Error: plugin is installed but unusable: failed to load plugin at "/home/runner/.local/share/helm/plugins/helm-unittest/plugin.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "platformHooks"
```